sudo: false

language: haskell

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_install:
  # Install stack as above
  # ...
  # Configure stack to use the system GHC installation
  - stack config --system-ghc set system-ghc --global true 
  - export PATH=/opt/ghc/7.10.2/bin:$PATH

install:
  - travis_wait stack --no-terminal --skip-ghc-check setup
  - travis_wait stack --no-terminal --skip-ghc-check test --only-snapshot

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.0.1


